// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARNep-NucBCnJT3462t912Kk6frTKC53k',
    appId: '1:294845155319:web:dbe9c4ffe72486d76650f2',
    messagingSenderId: '294845155319',
    projectId: 'todoapp-d4ed4',
    authDomain: 'todoapp-d4ed4.firebaseapp.com',
    storageBucket: 'todoapp-d4ed4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQomPzagl4fiEw4HVSQR2QQWc3IJa8Ew',
    appId: '1:294845155319:android:739fba851cae11876650f2',
    messagingSenderId: '294845155319',
    projectId: 'todoapp-d4ed4',
    storageBucket: 'todoapp-d4ed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRB48KfTm8cjpJjJ317Vg1daz5nIWRZdY',
    appId: '1:294845155319:ios:1a9cfd729c281a7c6650f2',
    messagingSenderId: '294845155319',
    projectId: 'todoapp-d4ed4',
    storageBucket: 'todoapp-d4ed4.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRB48KfTm8cjpJjJ317Vg1daz5nIWRZdY',
    appId: '1:294845155319:ios:1a9cfd729c281a7c6650f2',
    messagingSenderId: '294845155319',
    projectId: 'todoapp-d4ed4',
    storageBucket: 'todoapp-d4ed4.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARNep-NucBCnJT3462t912Kk6frTKC53k',
    appId: '1:294845155319:web:4cb8daca85b941186650f2',
    messagingSenderId: '294845155319',
    projectId: 'todoapp-d4ed4',
    authDomain: 'todoapp-d4ed4.firebaseapp.com',
    storageBucket: 'todoapp-d4ed4.appspot.com',
  );
}
